# Generated by Django 3.1 on 2020-11-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_patientdocconfig_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocconfig',
            name='access_code',
            field=models.IntegerField(default=1),
        ),
    ]
